id: P006842
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:26:06.620954
source_metadata:
  id: bdr:W10329
  title: མུས་ཆེན་སངས་རྒྱས་རྒྱལ་མཚན་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    e579858bd5b84b9fbe01ad6376c4419f:
      image_group_id: I1KG3597
      title: ''
      volume_number: 1
      total_pages: 578
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
